### ISSUE TITLE
10.0 Error

### ISSUE THREAD

**Issue by MetalHeadSeven** [ascott18/Masque-Skinner-Blizz-Buffs#2] opened 2022-10-27 21:31 UTC
Not working in 10.0

1x ...terface/AddOns/BlizzBuffsFacade/BlizzBuffsFacade.lua:30: 'for' limit must be a number
[string "@Interface/AddOns/BlizzBuffsFacade/BlizzBuffsFacade.lua"]:30: in function <...terface/AddOns/BlizzBuffsFacade/BlizzBuffsFacade.lua:13>

Locals:
self = Frame {
 0 = <userdata>
}
event = "PLAYER_ENTERING_WORLD"
addon = false
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = "DebuffButton1"
(*temporary) = "1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"
Buffs = <table> {
 db = <table> {
 }
 Parent = <table> {
 }
 Buttons = <table> {
 }
 ID = "Blizzard Buffs_Buffs"
 Group = "Buffs"
 Addon = "Blizzard Buffs"
}
Debuffs = <table> {
 db = <table> {
 }
 Parent = <table> {
 }
 Buttons = <table> {
 }
 ID = "Blizzard Buffs_Debuffs"
 Group = "Debuffs"
 Addon = "Blizzard Buffs"
}
TempEnchant = <table> {
 db = <table> {
 }
 Parent = <table> {
 }
 Buttons = <table> {
 }
 ID = "Blizzard Buffs_TempEnchant"
 Group = "TempEnchant"
 Addon = "Blizzard Buffs"
}
f = Frame {
 0 = <userdata>
}

**Comment by ascott18** [comment] 2022-10-29 03:24
Duplicate of #1

**Closed by ascott18** 2022-10-29 03:24 UTC
